version: "3.9"

services:
  druggpt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2026:2026"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: streamlit run ./druggpt/streamlit_app.py --server.port 2026 --theme.base light --server.maxMessageSize 500 --server.address=0.0.0.0
